events {}
http {
    server {
        listen 80;
        root /app;
        index index.php;
        location ~ \.php$ {
            fastcgi_pass fpm:9000;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            include fastcgi_params;
            fastcgi_read_timeout 120s;
        }
    }
}
